[package]
name = "scale-serialization"
description = "SCALE Serialization"
version = "1.0.0-beta2"
authors = ["Daniel Olano <daniel@olanod.com>"]
edition = "2021"
repository = "https://github.com/virto-network/scales"
license = "Apache-2.0"

[dependencies]
bytes = { version = "1.11", default-features = false }
scale-info = { version = "2.11", default-features = false, features = ["serde", "decode"], optional = true }
serde = { version = "1", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1", default-features = false, optional = true }
hex = { version = "0.4", default-features = false, features = ["alloc"], optional = true }
codec = { version = "3.7", package = "parity-scale-codec", default-features = false, optional = true }

[features]
default = ["std", "json", "hex", "scale-info", "serializer"]
serializer = []
compress = ["dep:scale-info", "serializer", "dep:codec"]
std = ["scale-info?/std", "bytes/std", "serde/std", "serde_json?/std"]
scale-info = ["dep:scale-info"]
json = ["dep:serde_json", "serde_json/preserve_order", "serde_json/alloc"]

[[bin]]
name = "compress"
required-features = ["std", "compress"]

[dev-dependencies]
anyhow = "1"
codec = { version = "3.7", package = "parity-scale-codec", default-features = false, features = ["derive"] }
scale-info = { version = "2.11", default-features = false, features = ["derive"] }
serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
