default: check

check:
    cargo check

lint:
    cargo clippy -- -D warnings

test:
    cargo test

check-no-std:
    cargo check --no-default-features
    cargo check --no-default-features --features serializer
    cargo check --no-default-features --features json
    cargo check --no-default-features --features text

check-thumbv7em:
    cargo check --target thumbv7em-none-eabihf --no-default-features

check-riscv32:
    cargo check --target riscv32imac-unknown-none-elf --no-default-features

check-wasm:
    cargo check --target wasm32-unknown-unknown --no-default-features

check-targets: check-no-std check-thumbv7em check-riscv32 check-wasm
