[package]
authors = ["Daniel Olano <me@olanod.com>"]
autoexamples = true
edition = "2021"
name = "libwallet"
version = "0.3.0"

[dependencies]
# base dependencies
arrayvec = {version = "0.7.2", default-features = false}

serde = {version = "1.0", default-features = false, features = ["derive"], optional = true}

# substrate seed derivation (PBKDF2-HMAC-SHA512)
hmac = {version = "0.12.1", default-features = false, optional = true}
pbkdf2 = {version = "0.11.0", default-features = false, optional = true}
sha2 = {version = "0.10.2", default-features = false, optional = true}

mnemonic = {package = "bip0039", version = "0.10.1", default-features = false, optional = true}

rand_core = {version = "0.6.3", optional = true}
# substrate related
schnorrkel = {version = "0.11.4", default-features = false, optional = true}# soft derivation in no_std
rand_chacha = {version = "0.3.1", default-features = false, optional = true}

# secp256k1/ethereum
k256 = {version = "0.13", default-features = false, features = ["ecdsa", "schnorr"], optional = true}
sha3 = {version = "0.10", default-features = false, optional = true}

# vault os
keyring = {version = "1.1.2", optional = true}
# vault pass
prs-lib = {version = "0.2.1", optional = true}
log = { version = "0.4" }
zeroize = { version = "1", default-features = false }

[dev-dependencies]
async-std = {version = "1.10.0", features = ["attributes"]}
serde_json = {version = "1.0", default-features = false, features = ["alloc"]}
# pass vault example
dirs = "4.0"


[features]
default = ["substrate"]
# default = ["std", "substrate", "vault_simple", "mnemonic", "rand", "vault_pass", "vault_os"]
rand = ["rand_core", "schnorrkel?/getrandom"]
secp256k1 = ["dep:k256"]
sr25519 = ["dep:schnorrkel", "dep:rand_chacha"]
std = [
  "rand_core/getrandom",
]
substrate = ["sr25519", "pbkdf2", "hmac", "sha2"]
ethereum = ["secp256k1", "dep:sha3", "pbkdf2", "hmac", "sha2"]
bitcoin = ["secp256k1", "pbkdf2", "hmac", "sha2"]
vault_os = ["keyring"]
vault_pass = ["prs-lib"]
vault_simple = ["mnemonic", "rand"]

[workspace]
