build:
    @mkdir -p dist
    cargo build --release --target wasm32-unknown-unknown
    @cp ./target/wasm32-unknown-unknown/release/vos_pass.wasm dist/
    wasm-bindgen --out-dir dist --target web --no-typescript --remove-name-section dist/vos_pass.wasm
    @cp src/pass.js dist/
