version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: virto-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - virto-network
    command: mongod --noauth

volumes:
  mongodb_data:

networks:
  virto-network:
    driver: bridge 