[package]
name = "sube"
description = "SUBmit Extrinsics to a Substrate node"
license = "Apache-2.0"
version = "1.0.0"
authors = ["Daniel Olano <daniel@olanod.com>"]
edition = "2021"
repository = "https://github.com/valibre-org/virto-dk/sube"

[dependencies]
blake2 = { version = "0.10", default-features = false }
codec = { version = "3.7", package = "parity-scale-codec", default-features = false }
frame-metadata = { version = "23", default-features = false, features = [
	"serde_full",
	"decode",
	"current",
] }
hex = { version = "0.4", default-features = false, features = ["alloc"] }
log = { version = "0.4", default-features = false }
scale-info = { version = "2.11", default-features = false }
scales = { path = "../scales", package = "scale-serialization", default-features = false, features = [
	"serializer",
	"compress",
	"json",
] }
serde = { version = "1", default-features = false }
serde_json = { version = "1", default-features = false, features = [
	"alloc",
	"arbitrary_precision",
] }
twox-hash = { version = "2.1", default-features = false, features = ["xxhash64"] }

# http backend
reqwest = { version = "0.13", optional = true, features = ["json"] }

# ws backend
futures-channel = { version = "0.3", default-features = false, features = [
	"alloc",
], optional = true }
futures-util = { version = "0.3", default-features = false, features = [
	"sink",
], optional = true }

async-tls = { version = "0.13", default-features = false, optional = true }

async-std = { version = "1.13", optional = true }
paste = { version = "1.0" }
wasm-bindgen = { version = "0.2", optional = true }
once_cell = { version = "1", optional = true }
heapless = "0.9"
anyhow = { version = "1", optional = true }
rand_core = { version = "0.6", optional = true }
ewebsock = { git = "https://github.com/S0c5/ewebsock.git", optional = true, branch = "enhacement/aviod-blocking-operations-with-mpsc-futures" }
no-std-async = "1.1"


[dev-dependencies]
async-std = { version = "1.13", features = ["attributes", "tokio1"] }
hex-literal = "1.1"
libwallet = { path = "../libwallet", default-features = false, features = [
	"substrate",
	"mnemonic",
	"sr25519",
	"util_pin",
	"rand",
	"std",
] }
rand_core = "0.6"

[features]
default = []
test = ["std", "wss", "http", "json", "dep:async-std", "dep:rand_core"]
http = ["dep:reqwest"]
http-web = ["dep:wasm-bindgen", "dep:reqwest"]
json = ["scales/json"]
text = ["scales/text"]
std = ["scales/std", "log/std", "serde/std", "serde_json/std", "hex/std"]

ws = [
	"dep:async-std",
	"dep:ewebsock",
	"dep:futures-channel",
	"dep:futures-util",
	"async-std/unstable",
]
wss = ["dep:async-tls", "ws", "ewebsock/tls", "async-std/unstable"]
examples = ["dep:rand_core"]
js = ["http-web", "json", 'async-std/unstable', "wss", "dep:rand_core"]

[package.metadata.docs.rs]
features = ["http"]

[workspace]
