build:
    # cargo clean --release --target wasm32-unknown-unknown
    @mkdir -p dist
    @cp src/*.js dist/
    cargo build --release --target wasm32-unknown-unknown
    @mv ./target/wasm32-unknown-unknown/release/vos_pass.wasm dist/
    wasm-bindgen --out-dir dist --target web --no-typescript --remove-name-section dist/vos_pass.wasm
    @echo 'await __wbg_init();' >> dist/vos_pass.js
