[package]
name = "sube-qemu-test"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
sube = { path = "../..", default-features = false, features = ["json", "text"] }
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7"
cortex-m-semihosting = "0.5"
panic-semihosting = "0.6"
embedded-alloc = "0.7"

[workspace]

[profile.release]
opt-level = "s"
lto = true
