name: Libwallet Publish

on:
  push:
    branches: [main]
    paths: ['lib/libwallet/**']

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      - name: Ensure access to npmjs
        run: npm whoami --registry https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Config git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Install dependencies
        working-directory: lib/libwallet/js
        run: npm ci

      - name: Build
        working-directory: lib/libwallet/js
        run: npm run build

      - name: Publish
        working-directory: lib/libwallet/js
        run: |
          npm version patch
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
