on: 
  pull_request:
    paths: ['lib/sube/**']

name: Sube

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v2

      - name: Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          source "$HOME/.cargo/env"

      - name: Check
        working-directory: lib/sube
        run: just check

      - name: Lint
        working-directory: lib/sube
        run: just lint
      